143 채팅방 이미지 기능 구현
Ogu-Family/Locomoco_BE pull request #223
Opened 2024-07-27 15:31 UTC by eugene225

## 🧙 PR 타입

- [X] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 🤨 Motivation

Resolved #143 

## 🔑 Key Changes

- 기존 웹소켓 통신에서 메시지만 전달하던 부분에 이미지도 함께 전달할 수 있도록 변경
- 해당 기능 테스트 코드 작성

## 🙏 To Reviewers

byteCode로 변환한 이미지 [프론트] -> String 변환 [프론트] -> dto List에 담아 서버로 전달됨 [프론트 -> 백]
위의 과정을 거쳐 프론트에서 백엔드로 이미지를 전달하고, 백엔드에서는 s3에 저장 후 url 리스트만 프론트에 반환합니다.
코드가 어색한 부분이나, 개선되었으면 하는 부분 있으면 코멘트 남겨주세요 !!

2024-07-29 09:25 UTC, ZZAMBAs requested changes
이미지 채팅까지 구현하시니 채팅에 대한 모든 것을 구현하신 것 같아요~ 고생하셨습니다!! 

아래에 코멘트 남겼습니다. 그런데 제가 잘못 이해하고 작성한 것이 있을 수도 있어요. 확인해주시고 답변 해주시면 감사할 것 같아요~

Request changes를 한 이유는 제 생각에 확장자를 얻어오는 로직이 잘못된 것 같다고 느꼈기 때문이에요. 실제 테스트 코드에서도 스누피가 .jpeg가 아닌 .jpg로 저장되었습니다!

2024-07-29 09:25 UTC, ZZAMBAs commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +                return format;
앞에서부터 확인하면 확장자가 뒤에 있어서 이 코드를 타지 못할 것 같은데 맞을까요?

2024-07-29 09:25 UTC, ZZAMBAs commented on src/main/java/org/prgms/locomocoserver/chat/application/MySqlChatMessageService.java
> +        return null;
null로 반환하면 즉시 이상함을 느낄 수 없을 것 같아요. 안 쓰는 메서드이긴 하지만 예외로 반환하는 것이 낫다고 생각합니다. Java에서 `UnsupportedException`을 지원하는데 이를 사용하는 건 어떻게 생각하시나요?

2024-07-29 09:25 UTC, ZZAMBAs commented on src/test/java/org/prgms/locomocoserver/chat/application/MongoChatServiceTest.java
>          assertThat(messageCount).isEqualTo(2);
제 로컬에서 실행했더니 여기부분에서 예외가 나더라구요. 제가 실행할 때는 메시지가 1개였어서 그런 것 같아요. 따로 컬렉션 사이즈를 미리 테스트 코드 앞에서 계산한 뒤에 테스트 후 사이즈가 전보다 1 증가했는지 검증하는 것은 어떨까요? 예를 들면 아래처럼요?
```suggestion
        assertThat(messageCount).isEqualTo(beforeMessageSize + 1);
```

2024-07-29 13:04 UTC, eugene225 commented on src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
> +        List<String> imageByteCode
웹소켓으로 이미지를 전달할 때에는 bytecode로 전달할 수 없고, String으로 변환해야 전송이 가능하다고 합니다
그래서 프론트에서 ByteCode가 String 값으로 변환되어 넘어옵니다..!

2024-07-29 13:06 UTC, eugene225 commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +            // Base64 인코딩된 이미지 데이터에서 바이트 배열로 디코딩
STOMP를 활용한 웹소켓 통신에서는 bytecode를 직접 전달할 수 없다고 합니다..!

2024-07-29 13:07 UTC, eugene225 commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +                return format;
..! 수정해야될 것 같습니다ㅜ

2024-07-29 13:07 UTC, eugene225 commented on src/main/java/org/prgms/locomocoserver/chat/application/MySqlChatMessageService.java
> +        return null;
좋은생각인 것 같습니다 !

2024-07-29 13:07 UTC, eugene225 commented on src/test/java/org/prgms/locomocoserver/chat/application/MongoChatServiceTest.java
>          assertThat(messageCount).isEqualTo(2);
좋은 생각인 것 같습니다 ! 수정하겠습니당

2024-08-10 16:06 UTC, ZZAMBAs approved these changes
고생 많으셨습니다!

2024-08-10 16:06 UTC, ZZAMBAs commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +    private static final byte[] HEIC_HEADER = new byte[]{'f', 't', 'y', 'p'};
오 이 방식은 어떻게 동작하는 걸까요?

2024-08-11 06:33 UTC, eugene225 commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +    private static final byte[] HEIC_HEADER = new byte[]{'f', 't', 'y', 'p'};
[파일 시그니처 헤더](https://velog.io/@910/%ED%8C%8C%EC%9D%BC-%EC%8B%9C%EA%B7%B8%EB%8B%88%EC%B2%98File-Signatures-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0) byte코드를 String으로 다시 변환하여 . 아래쪽의 확장자를 확인하는데에는 성능상 문제가 있을 것 같아, 파일별로 가지고 있는 바이트 코드의 시그니처를 비교하는 방식으로 구현하였습니다..!

2024-08-11 15:32 UTC, ZZAMBAs commented
`develop` 브랜치 머지 후에 다시 워크 플로 실행해 주세요. 에러가 일어난 부분 `develop`에서 직접 수정했습니다!

2024-08-11 15:32 UTC, ZZAMBAs commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +    private static final byte[] HEIC_HEADER = new byte[]{'f', 't', 'y', 'p'};
heic 파일은 무엇인가요?

2024-08-12 06:11 UTC, eugene225 commented on src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
> +    private static final byte[] HEIC_HEADER = new byte[]{'f', 't', 'y', 'p'};
mac 기반 기기에서 적용되는 이미지 파일 형식입니다..!
[참고글](https://amdu.tistory.com/13)

2024-08-12 06:21 UTC, merged